#!/usr/bin/env node

var fs = require("fs");
var path = require('path');
var watchify = require('watchify');
var browserify = require('browserify');
var babelify = require("babelify");
var exorcist = require("exorcist");

var srcPath = "./js/";
var distPath = "./js-dist";

var bundler = watchify(browserify({
    debug: true,
    entries: ['./js/main.js'],
    transform: "babelify",
    cache: {}, packageCache: {}, fullPaths: true
  }))
  .on("update", function () {
    var updateStart = Date.now();
    console.log(updateStart);
    return bundler
      .bundle()
      .pipe(exorcist(path.join(distPath, "bundle.js.map")))
      .pipe(fs.createWriteStream(path.join(distPath, "bundle.js")));
  })
  .bundle()
  .pipe(exorcist(path.join(distPath, "bundle.js.map")))
  .pipe(fs.createWriteStream(path.join(distPath, "bundle.js")));